name: Gerar APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Instalar Java e ferramentas Android
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar APK com Buildozer
        uses: ArtemisAnatol/buildozer-action@v1
        with:
          command: buildozer android debug
          repository_root: .

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: meu-aplicativo-debug
          path: ./.buildozer/android/app/build/outputs/apk/debug/*.apk
