name: Gerar APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Limpar cache do Buildozer
        run: buildozer android clean
  
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Python Estavel (3.11)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar ferramentas de compilacao do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache cmake git libffi-dev libssl-dev zip unzip lld libncurses-dev autoconf automake libtool libltdl-dev pkg-config zlib1g-dev gawk patch libsqlite3-dev libbz2-dev gettext

      - name: Instalar Buildozer Estável
        run: |
          pip install --upgrade pip setuptools wheel virtualenv "cython<=3.0.12"
          pip install buildozer
    

      - name: Compilar APK com Buildozer (Modo Verbose)
        env:
          CFLAGS: "-Wno-error=incompatible-pointer-types"
        run: |
          yes | buildozer -v android debug

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: meu-aplicativo-debug
          path: bin/*.apk
          
